name: Create Release

on:
  push:
    tags:
      - "*v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for MacOS x64
      run: env GOOS=darwin GOARCH=amd64 go build -v -o ./bin/lively-macos-x64 .

    - name: Build for Linux x64
      run: env GOOS=linux GOARCH=amd64 go build -v -o ./bin/lively-linux-x64 .

    - name: Build for Windows x64
      run: env GOOS=windows GOARCH=amd64 go build -v -o ./bin/lively-windows-x64 .

    - name: Create Pre-release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v0.')
      with:
        prerelease: true
        files: ./bin/*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      with:
        files: ./bin/*